"""make request number nullable

Revision ID: 32c976491925
Revises: 739378d0ac32
Create Date: 2026-09-22 13:42:29.905177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c976491925'
down_revision: Union[str, Sequence[str], None] = '739378d0ac32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
